### ISSUE TITLE
DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM does not work

### ISSUE THREAD

**Issue by SinZ163** [ModDota/BugTracker#84]
When using:
```js
GameUI.SetDefaultUIEnabled(DotaDefaultUIElement_t.DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM, false);
```
it does not hide radiant team hero icons nor their colour bar at the top, in contrast to
```js
GameUI.SetDefaultUIEnabled(DotaDefaultUIElement_t.DOTA_DEFAULT_UI_TOP_BAR_DIRE_TEAM, false);
```
which works as expected as demonstrated in DarkMoon

The bug is likely due to how all of these work by applying a class to `<DOTAHud />` and [when you compare the CSS definitions of the two...](https://github.com/SteamDatabase/GameTracking-Dota2/blob/c6a10d9fc4eae2aff810c9893377d675ddf3ffc4/game/dota/pak01_dir/panorama/styles/hud/dota_hud_top_bar.css#L826-L836)

```css
.HIDE_TOP_BAR_RADIANT_TEAM
{
	visibility: collapse;
}

.HIDE_TOP_BAR_DIRE_TEAM #TopBarDireTeam,
.HIDE_TOP_BAR_DIRE_TEAM #TopBarRightFlare,
.HIDE_TOP_BAR_DIRE_TEAM #TopBarDireScore
{
	visibility: collapse;
}
```

It is clear that its not working as intended.
